apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: infotrygd-enslig-forsoerger
  namespace: infotrygd
  labels:
    team: infotrygd

spec:
  image: {{ image }}
  port: 8080 # Required. The port number which is exposed by the container and should receive HTTP traffic.
  liveness:
    path: /internal/status/isAlive
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas: # Optional. Set min = max to disable autoscaling.
    min: 2 # minimum number of replicas.
    max: 5 # maximum number of replicas.
    cpuThresholdPercentage: 50 # total cpu percentage threshold on deployment, at which point it will increase number of pods if current < max
  leaderElection: false # Optional. If true, a http endpoint will be available at $ELECTOR_PATH that return the current leader
  # Compare this value with the $HOSTNAME to see if the current instance is the leader
  preStopHookPath: "" # Optional. A HTTP GET will be issued to this endpoint at least once before the pod is terminated.
  # See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  istio: # Optional.
    enabled: false # Optional. When true, envoy-proxy sidecar will be injected into pod and https urls envvars will be rewritten
  resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
    limits:
      cpu: 1500m # app will have its cpu usage throttled if exceeding this limit
      memory: 512Mi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: 500m
      memory: 256Mi
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://infotrygd-enslig-forsoerger.nais.adeo.no
    - https://infotrygd-enslig-forsoerger.prod-fss-pub.nais.io
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  vault:
    enabled: true # Optional. If set to true fetch secrets from Secret Service and inject into the pods. todo link to doc.
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
          namespace: default
        - application: familie-ef-sak
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-ef-mottak
          namespace: teamfamilie
  env:
    - name: APP_DATASOURCE_URL
      value: jdbc:oracle:thin:@a01dbfl037.adeo.no:1521/cdc
    - name: APP_DATASOURCE_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DATASOURCE_DRIVER
      value: oracle.jdbc.driver.OracleDriver
    - name: APP_JPA_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DEFAULT_SCHEMA
      value: REST_READ_P
    - name: APP_AZURE_PROXY_URL
      value: https://webproxy-nais.nav.no:8088
    - name: APP_CLIENT_WHITELIST
      value: 1da8f976-2cc4-43a4-91f7-11d2e27e593c, 56242d34-609b-4a7a-bdb2-79841f2e53c4